name: Build SKSE Plugin

on:
  push:
    branches: [ main, feature/ini-editor ]
  pull_request:
    branches: [ main, feature/ini-editor ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      SKYRIM_MODS_FOLDER: ${{ github.workspace }}\dummy-mods
      SKYRIM_FOLDER: ${{ github.workspace }}\dummy-skyrim

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install MSVC (toolchain)
        uses: microsoft/setup-msbuild@v2

      - name: Create dummy folders for env vars
        run: |
          mkdir "${{ env.SKYRIM_MODS_FOLDER }}"
          mkdir "${{ env.SKYRIM_FOLDER }}"
          mkdir "${{ env.SKYRIM_FOLDER }}\Data"

      # Tidak perlu clone CommonLibSSE atau install vcpkg/imgui
      # karena CommonLibSSE dari submodule dan ImGui dari extern/imgui

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload built DLL
        uses: actions/upload-artifact@v4
        with:
          name: SKSE-plugin-dll
          path: |
            build/Release/*.dll
            build/*.dll
            ${{ env.SKYRIM_MODS_FOLDER }}/**/*.dll
